### ISSUE TITLE
Add rules for indentation

### ISSUE THREAD

**Issue by rugk** [carrot/markdown-styleguide#4]
I would recommend two spaces.

**Comment by notslang** [comment]
I think we've got indentation rules:

> Nested list items must be indented 2 spaces further than their parent.

Unless you mean rules for code within code blocks... If that's what you're talking about, then I'd disagree. Code blocks should just follow the rules of the language that they're written in (like Makefile examples needing to be tab-indented, or proper Python examples using 4 spaces).

**Comment by notslang** [comment]
Closing this for now, but if there's something I missed or am wrong about, please comment/reopen.

**Comment by rugk** [comment]
> I think we've got indentation rules:
> 
> > Nested list items must be indented 2 spaces further than their parent.

Okay did not saw this. This is mostly what I wanted.
